version: "3.8"

services:
  # Development service
  website-dev:
    container_name: personal-website-dev
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev
    restart: unless-stopped

  # Production service
  website-prod:
    container_name: personal-website-prod
    build:
      context: .
      target: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
