site_name: Documentation - Simon Stijnen Portfolio
site_description: Comprehensive documentation for Simon Stijnen's portfolio website built with Next.js 15, TypeScript, and Tailwind CSS
site_author: Simon Stijnen
site_url: https://simonstnn.github.io/website/
repo_url: https://github.com/SimonStnn/website
copyright: Copyright &copy; 2025 Simon Stijnen

docs_dir: ../../docs

theme:
  name: material
  locale: en
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme)"
      primary: teal
      accent: yellow
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      primary: teal
      accent: yellow
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: teal
      accent: yellow
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tabs
    - navigation.path
    - navigation.prune
    - navigation.top
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/
    - navigation.footer
    # - navigation.sections
    - toc.follow
    # - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
  - admonition
  - footnotes
  - toc:
      permalink: true
  - attr_list
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-previews
  - material.extensions.preview:
      configurations:
        - targets:
            include:
              - "*"

plugins:
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/
  - search
  - mkdocs-pdf
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/
  # - social
  # https://squidfunk.github.io/mkdocs-material/setup/building-an-optimized-site/#built-in-optimize-plugin
  - optimize

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/simon-stijnen/
