name: CI

on:
  push:
  pull_request:

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: |
          npm run lint

      - name: Run format check
        run: |
          npm run format:check

      - name: Run tests
        run: |
          npm test

  build-and-push:
    needs: continuous-integration
    if: github.ref == 'refs/heads/main-v2'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Extract version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f1-2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "MAJOR=$MAJOR" >> $GITHUB_ENV
          echo "MINOR=$MINOR" >> $GITHUB_ENV
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/SimonStnn/website:latest
            ghcr.io/SimonStnn/website:${{ env.MAJOR }}
            ghcr.io/SimonStnn/website:${{ env.MINOR }}
            ghcr.io/SimonStnn/website:${{ env.VERSION }}
            ghcr.io/SimonStnn/website:${{ github.sha }}
